### ISSUE TITLE
Kill tracking in redzones

### ISSUE THREAD

**Issue by Lewis-Development** [Scarso327/AltisLife-Framework#352]
- [x] Zone entrance text
- [ ] Track kills
- [ ] Display K/D on Profile page
- [ ] Method to view top 3 players (kills)
